/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package speed.click;

/**
 *
 * @author daphn
 */
public class InterfacePartie16x16classique extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePartie16x16classique
     */
    public InterfacePartie16x16classique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneaugrille_16x16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();
        jButton226 = new javax.swing.JButton();
        jButton227 = new javax.swing.JButton();
        jButton228 = new javax.swing.JButton();
        jButton229 = new javax.swing.JButton();
        jButton230 = new javax.swing.JButton();
        jButton231 = new javax.swing.JButton();
        jButton232 = new javax.swing.JButton();
        jButton233 = new javax.swing.JButton();
        jButton234 = new javax.swing.JButton();
        jButton235 = new javax.swing.JButton();
        jButton236 = new javax.swing.JButton();
        jButton237 = new javax.swing.JButton();
        jButton238 = new javax.swing.JButton();
        jButton239 = new javax.swing.JButton();
        jButton240 = new javax.swing.JButton();
        jButton241 = new javax.swing.JButton();
        jButton242 = new javax.swing.JButton();
        jButton243 = new javax.swing.JButton();
        jButton244 = new javax.swing.JButton();
        jButton245 = new javax.swing.JButton();
        jButton246 = new javax.swing.JButton();
        jButton247 = new javax.swing.JButton();
        jButton248 = new javax.swing.JButton();
        jButton249 = new javax.swing.JButton();
        jButton250 = new javax.swing.JButton();
        jButton251 = new javax.swing.JButton();
        jButton252 = new javax.swing.JButton();
        jButton253 = new javax.swing.JButton();
        jButton254 = new javax.swing.JButton();
        jButton255 = new javax.swing.JButton();
        jButton256 = new javax.swing.JButton();
        panneaumodepartie = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        chronometre2 = new javax.swing.JPanel();
        chronometre1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        START = new javax.swing.JButton();
        infosjoueur2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scorejoueur6 = new javax.swing.JLabel();
        nomjoueur6 = new javax.swing.JLabel();
        recordnomjoueur6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panneaugrille_16x16.setBackground(new java.awt.Color(204, 255, 255));
        Panneaugrille_16x16.setLayout(new java.awt.GridLayout(16, 16));
        Panneaugrille_16x16.add(jButton1);
        Panneaugrille_16x16.add(jButton2);
        Panneaugrille_16x16.add(jButton3);
        Panneaugrille_16x16.add(jButton4);
        Panneaugrille_16x16.add(jButton5);
        Panneaugrille_16x16.add(jButton6);
        Panneaugrille_16x16.add(jButton7);
        Panneaugrille_16x16.add(jButton8);
        Panneaugrille_16x16.add(jButton9);
        Panneaugrille_16x16.add(jButton10);
        Panneaugrille_16x16.add(jButton11);
        Panneaugrille_16x16.add(jButton12);
        Panneaugrille_16x16.add(jButton13);
        Panneaugrille_16x16.add(jButton14);
        Panneaugrille_16x16.add(jButton15);
        Panneaugrille_16x16.add(jButton16);
        Panneaugrille_16x16.add(jButton17);
        Panneaugrille_16x16.add(jButton18);
        Panneaugrille_16x16.add(jButton19);
        Panneaugrille_16x16.add(jButton20);
        Panneaugrille_16x16.add(jButton21);
        Panneaugrille_16x16.add(jButton22);
        Panneaugrille_16x16.add(jButton23);
        Panneaugrille_16x16.add(jButton24);
        Panneaugrille_16x16.add(jButton25);
        Panneaugrille_16x16.add(jButton26);
        Panneaugrille_16x16.add(jButton27);
        Panneaugrille_16x16.add(jButton28);
        Panneaugrille_16x16.add(jButton29);
        Panneaugrille_16x16.add(jButton30);
        Panneaugrille_16x16.add(jButton31);
        Panneaugrille_16x16.add(jButton32);
        Panneaugrille_16x16.add(jButton33);
        Panneaugrille_16x16.add(jButton34);
        Panneaugrille_16x16.add(jButton35);
        Panneaugrille_16x16.add(jButton36);
        Panneaugrille_16x16.add(jButton37);
        Panneaugrille_16x16.add(jButton38);
        Panneaugrille_16x16.add(jButton39);
        Panneaugrille_16x16.add(jButton40);
        Panneaugrille_16x16.add(jButton41);
        Panneaugrille_16x16.add(jButton42);
        Panneaugrille_16x16.add(jButton43);
        Panneaugrille_16x16.add(jButton44);
        Panneaugrille_16x16.add(jButton45);
        Panneaugrille_16x16.add(jButton46);
        Panneaugrille_16x16.add(jButton47);
        Panneaugrille_16x16.add(jButton48);
        Panneaugrille_16x16.add(jButton49);
        Panneaugrille_16x16.add(jButton50);
        Panneaugrille_16x16.add(jButton51);
        Panneaugrille_16x16.add(jButton52);
        Panneaugrille_16x16.add(jButton53);
        Panneaugrille_16x16.add(jButton54);
        Panneaugrille_16x16.add(jButton55);
        Panneaugrille_16x16.add(jButton56);
        Panneaugrille_16x16.add(jButton57);
        Panneaugrille_16x16.add(jButton58);
        Panneaugrille_16x16.add(jButton59);
        Panneaugrille_16x16.add(jButton60);
        Panneaugrille_16x16.add(jButton61);
        Panneaugrille_16x16.add(jButton62);
        Panneaugrille_16x16.add(jButton63);
        Panneaugrille_16x16.add(jButton64);
        Panneaugrille_16x16.add(jButton65);
        Panneaugrille_16x16.add(jButton66);
        Panneaugrille_16x16.add(jButton67);
        Panneaugrille_16x16.add(jButton68);
        Panneaugrille_16x16.add(jButton69);
        Panneaugrille_16x16.add(jButton70);
        Panneaugrille_16x16.add(jButton71);
        Panneaugrille_16x16.add(jButton72);
        Panneaugrille_16x16.add(jButton73);
        Panneaugrille_16x16.add(jButton74);
        Panneaugrille_16x16.add(jButton75);
        Panneaugrille_16x16.add(jButton76);
        Panneaugrille_16x16.add(jButton77);
        Panneaugrille_16x16.add(jButton78);
        Panneaugrille_16x16.add(jButton79);
        Panneaugrille_16x16.add(jButton80);
        Panneaugrille_16x16.add(jButton81);
        Panneaugrille_16x16.add(jButton82);
        Panneaugrille_16x16.add(jButton83);
        Panneaugrille_16x16.add(jButton84);
        Panneaugrille_16x16.add(jButton85);
        Panneaugrille_16x16.add(jButton86);
        Panneaugrille_16x16.add(jButton87);
        Panneaugrille_16x16.add(jButton88);
        Panneaugrille_16x16.add(jButton89);
        Panneaugrille_16x16.add(jButton90);
        Panneaugrille_16x16.add(jButton91);
        Panneaugrille_16x16.add(jButton92);
        Panneaugrille_16x16.add(jButton93);
        Panneaugrille_16x16.add(jButton94);
        Panneaugrille_16x16.add(jButton95);
        Panneaugrille_16x16.add(jButton96);
        Panneaugrille_16x16.add(jButton97);
        Panneaugrille_16x16.add(jButton98);
        Panneaugrille_16x16.add(jButton99);
        Panneaugrille_16x16.add(jButton100);
        Panneaugrille_16x16.add(jButton101);
        Panneaugrille_16x16.add(jButton102);
        Panneaugrille_16x16.add(jButton103);
        Panneaugrille_16x16.add(jButton104);
        Panneaugrille_16x16.add(jButton105);
        Panneaugrille_16x16.add(jButton106);
        Panneaugrille_16x16.add(jButton107);
        Panneaugrille_16x16.add(jButton108);
        Panneaugrille_16x16.add(jButton109);
        Panneaugrille_16x16.add(jButton110);
        Panneaugrille_16x16.add(jButton111);
        Panneaugrille_16x16.add(jButton112);
        Panneaugrille_16x16.add(jButton113);
        Panneaugrille_16x16.add(jButton114);
        Panneaugrille_16x16.add(jButton115);
        Panneaugrille_16x16.add(jButton116);
        Panneaugrille_16x16.add(jButton117);
        Panneaugrille_16x16.add(jButton118);
        Panneaugrille_16x16.add(jButton119);
        Panneaugrille_16x16.add(jButton120);
        Panneaugrille_16x16.add(jButton121);
        Panneaugrille_16x16.add(jButton122);
        Panneaugrille_16x16.add(jButton123);
        Panneaugrille_16x16.add(jButton124);
        Panneaugrille_16x16.add(jButton125);
        Panneaugrille_16x16.add(jButton126);
        Panneaugrille_16x16.add(jButton127);
        Panneaugrille_16x16.add(jButton128);
        Panneaugrille_16x16.add(jButton129);
        Panneaugrille_16x16.add(jButton130);
        Panneaugrille_16x16.add(jButton131);
        Panneaugrille_16x16.add(jButton132);
        Panneaugrille_16x16.add(jButton133);
        Panneaugrille_16x16.add(jButton134);
        Panneaugrille_16x16.add(jButton135);
        Panneaugrille_16x16.add(jButton136);
        Panneaugrille_16x16.add(jButton137);
        Panneaugrille_16x16.add(jButton138);
        Panneaugrille_16x16.add(jButton139);
        Panneaugrille_16x16.add(jButton140);
        Panneaugrille_16x16.add(jButton141);
        Panneaugrille_16x16.add(jButton142);
        Panneaugrille_16x16.add(jButton143);
        Panneaugrille_16x16.add(jButton144);
        Panneaugrille_16x16.add(jButton145);
        Panneaugrille_16x16.add(jButton146);
        Panneaugrille_16x16.add(jButton147);
        Panneaugrille_16x16.add(jButton148);
        Panneaugrille_16x16.add(jButton149);
        Panneaugrille_16x16.add(jButton150);
        Panneaugrille_16x16.add(jButton151);
        Panneaugrille_16x16.add(jButton152);
        Panneaugrille_16x16.add(jButton153);
        Panneaugrille_16x16.add(jButton154);
        Panneaugrille_16x16.add(jButton155);
        Panneaugrille_16x16.add(jButton156);
        Panneaugrille_16x16.add(jButton157);
        Panneaugrille_16x16.add(jButton158);
        Panneaugrille_16x16.add(jButton159);
        Panneaugrille_16x16.add(jButton160);
        Panneaugrille_16x16.add(jButton161);
        Panneaugrille_16x16.add(jButton162);
        Panneaugrille_16x16.add(jButton163);
        Panneaugrille_16x16.add(jButton164);
        Panneaugrille_16x16.add(jButton165);
        Panneaugrille_16x16.add(jButton166);
        Panneaugrille_16x16.add(jButton167);
        Panneaugrille_16x16.add(jButton168);
        Panneaugrille_16x16.add(jButton169);
        Panneaugrille_16x16.add(jButton170);
        Panneaugrille_16x16.add(jButton171);
        Panneaugrille_16x16.add(jButton172);
        Panneaugrille_16x16.add(jButton173);
        Panneaugrille_16x16.add(jButton174);
        Panneaugrille_16x16.add(jButton175);
        Panneaugrille_16x16.add(jButton176);
        Panneaugrille_16x16.add(jButton177);
        Panneaugrille_16x16.add(jButton178);
        Panneaugrille_16x16.add(jButton179);
        Panneaugrille_16x16.add(jButton180);
        Panneaugrille_16x16.add(jButton181);
        Panneaugrille_16x16.add(jButton182);
        Panneaugrille_16x16.add(jButton183);
        Panneaugrille_16x16.add(jButton184);
        Panneaugrille_16x16.add(jButton185);
        Panneaugrille_16x16.add(jButton186);
        Panneaugrille_16x16.add(jButton187);
        Panneaugrille_16x16.add(jButton188);
        Panneaugrille_16x16.add(jButton189);
        Panneaugrille_16x16.add(jButton190);
        Panneaugrille_16x16.add(jButton191);
        Panneaugrille_16x16.add(jButton192);
        Panneaugrille_16x16.add(jButton193);
        Panneaugrille_16x16.add(jButton194);
        Panneaugrille_16x16.add(jButton195);
        Panneaugrille_16x16.add(jButton196);
        Panneaugrille_16x16.add(jButton197);
        Panneaugrille_16x16.add(jButton198);
        Panneaugrille_16x16.add(jButton199);
        Panneaugrille_16x16.add(jButton200);
        Panneaugrille_16x16.add(jButton201);
        Panneaugrille_16x16.add(jButton202);
        Panneaugrille_16x16.add(jButton203);
        Panneaugrille_16x16.add(jButton204);
        Panneaugrille_16x16.add(jButton205);
        Panneaugrille_16x16.add(jButton206);
        Panneaugrille_16x16.add(jButton207);
        Panneaugrille_16x16.add(jButton208);
        Panneaugrille_16x16.add(jButton209);
        Panneaugrille_16x16.add(jButton210);
        Panneaugrille_16x16.add(jButton211);
        Panneaugrille_16x16.add(jButton212);
        Panneaugrille_16x16.add(jButton213);
        Panneaugrille_16x16.add(jButton214);
        Panneaugrille_16x16.add(jButton215);
        Panneaugrille_16x16.add(jButton216);
        Panneaugrille_16x16.add(jButton217);
        Panneaugrille_16x16.add(jButton218);
        Panneaugrille_16x16.add(jButton219);
        Panneaugrille_16x16.add(jButton220);
        Panneaugrille_16x16.add(jButton221);
        Panneaugrille_16x16.add(jButton222);
        Panneaugrille_16x16.add(jButton223);
        Panneaugrille_16x16.add(jButton224);
        Panneaugrille_16x16.add(jButton225);
        Panneaugrille_16x16.add(jButton226);
        Panneaugrille_16x16.add(jButton227);
        Panneaugrille_16x16.add(jButton228);
        Panneaugrille_16x16.add(jButton229);
        Panneaugrille_16x16.add(jButton230);
        Panneaugrille_16x16.add(jButton231);
        Panneaugrille_16x16.add(jButton232);
        Panneaugrille_16x16.add(jButton233);
        Panneaugrille_16x16.add(jButton234);
        Panneaugrille_16x16.add(jButton235);
        Panneaugrille_16x16.add(jButton236);
        Panneaugrille_16x16.add(jButton237);
        Panneaugrille_16x16.add(jButton238);
        Panneaugrille_16x16.add(jButton239);
        Panneaugrille_16x16.add(jButton240);
        Panneaugrille_16x16.add(jButton241);
        Panneaugrille_16x16.add(jButton242);
        Panneaugrille_16x16.add(jButton243);
        Panneaugrille_16x16.add(jButton244);
        Panneaugrille_16x16.add(jButton245);
        Panneaugrille_16x16.add(jButton246);
        Panneaugrille_16x16.add(jButton247);
        Panneaugrille_16x16.add(jButton248);
        Panneaugrille_16x16.add(jButton249);
        Panneaugrille_16x16.add(jButton250);
        Panneaugrille_16x16.add(jButton251);
        Panneaugrille_16x16.add(jButton252);
        Panneaugrille_16x16.add(jButton253);
        Panneaugrille_16x16.add(jButton254);
        Panneaugrille_16x16.add(jButton255);
        Panneaugrille_16x16.add(jButton256);

        getContentPane().add(Panneaugrille_16x16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 700, 700));

        panneaumodepartie.setBackground(new java.awt.Color(255, 153, 255));
        panneaumodepartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Bienvenue dans la Partie 16x16 classique !");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panneaumodepartie.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 307, 48));

        getContentPane().add(panneaumodepartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 380, -1));

        chronometre2.setBackground(new java.awt.Color(255, 255, 204));
        chronometre2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chronometre1.setBackground(new java.awt.Color(255, 255, 204));
        chronometre1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        chronometre2.add(chronometre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 310, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chronomètre : ");
        chronometre2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        START.setText("START");
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });
        chronometre2.add(START, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        getContentPane().add(chronometre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 310, 130));

        infosjoueur2.setBackground(new java.awt.Color(255, 255, 204));
        infosjoueur2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Infos Joueurs : ");
        infosjoueur2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        scorejoueur6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        scorejoueur6.setText("scorejoueur6");
        infosjoueur2.add(scorejoueur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, 20));

        nomjoueur6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomjoueur6.setText("nomjoueur6");
        infosjoueur2.add(nomjoueur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, 20));

        recordnomjoueur6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recordnomjoueur6.setText("reccordnomjoueur6");
        infosjoueur2.add(recordnomjoueur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Score : ");
        infosjoueur2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));
        infosjoueur2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nom : ");
        infosjoueur2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Reccord : ");
        infosjoueur2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 20));

        getContentPane().add(infosjoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 310, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STARTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePartie16x16classique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePartie16x16classique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePartie16x16classique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePartie16x16classique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePartie16x16classique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panneaugrille_16x16;
    private javax.swing.JButton START;
    private javax.swing.JPanel chronometre1;
    private javax.swing.JPanel chronometre2;
    private javax.swing.JPanel infosjoueur2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JButton jButton226;
    private javax.swing.JButton jButton227;
    private javax.swing.JButton jButton228;
    private javax.swing.JButton jButton229;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton230;
    private javax.swing.JButton jButton231;
    private javax.swing.JButton jButton232;
    private javax.swing.JButton jButton233;
    private javax.swing.JButton jButton234;
    private javax.swing.JButton jButton235;
    private javax.swing.JButton jButton236;
    private javax.swing.JButton jButton237;
    private javax.swing.JButton jButton238;
    private javax.swing.JButton jButton239;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton240;
    private javax.swing.JButton jButton241;
    private javax.swing.JButton jButton242;
    private javax.swing.JButton jButton243;
    private javax.swing.JButton jButton244;
    private javax.swing.JButton jButton245;
    private javax.swing.JButton jButton246;
    private javax.swing.JButton jButton247;
    private javax.swing.JButton jButton248;
    private javax.swing.JButton jButton249;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton250;
    private javax.swing.JButton jButton251;
    private javax.swing.JButton jButton252;
    private javax.swing.JButton jButton253;
    private javax.swing.JButton jButton254;
    private javax.swing.JButton jButton255;
    private javax.swing.JButton jButton256;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nomjoueur6;
    private javax.swing.JPanel panneaumodepartie;
    private javax.swing.JLabel recordnomjoueur6;
    private javax.swing.JLabel scorejoueur6;
    // End of variables declaration//GEN-END:variables
}
